##############################################################################
#
#   Copyright (c) 2019 AT&T Intellectual Property.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
##############################################################################

#
#   This source code is part of the near-RT RIC (RAN Intelligent Controller)
#   platform project (RICP).
#
FROM e2term-base:bronze as ricbuild

WORKDIR /opt/e2/

ARG BUILD_TYPE="Release"

# RUN mkdir -p /opt/e2/RIC-E2-TERMINATION/

# COPY . /opt/e2/RIC-E2-TERMINATION/ 

COPY ./sctpThread.cpp /opt/e2/RIC-E2-TERMINATION/sctpThread.cpp
COPY ./sctpThread.h /opt/e2/RIC-E2-TERMINATION/sctpThread.h

# apt-get update &&
RUN make -j ${nproc} && make install && ldconfig \
    && cd /opt/e2/ && /usr/local/bin/cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE . && make -j ${nproc} \
    && echo "3" > /opt/e2/rmr.verbose

WORKDIR /opt/e2/
ENV LD_LIBRARY_PATH=/usr/local/lib
ENV RMR_SEED_RT=dockerRouter.txt
ENV E2TERM_POD_NAME=e2term
RUN chmod +x /opt/e2/startup.sh
EXPOSE 38000
CMD ["sh", "-c", "./startup.sh"]
